version: '3.8'

services:
        web:
                image: odoo
                ports: 
                        - "8069:8069"
                links:
                        - db
                environment:
                        - HOST=db
                        - USER=odoo
                        - PASSWORD=odoo
        
        db:
                image: postgres:10
                environment:
                        POSTGRES_USER: odoo
                        POSTGRES_PASSWORD: odoo
                        POSTGRES_DB: postgres
